[database]
network = "tcp"
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
database = "opencars"
max_retries = 0
pool = 10

[hsc]
host = "http://api.hsc.gov.ua"

[api]
host = "localhost"
port = 8080
